const Projects = [
  {
    id: 11,
    title: "Calculator",
    text: "Calculator app built with React and TypeScript.",
    preview: "https://bozidarboze.github.io/calculator/",
    code: "https://github.com/Bozidarboze/calculator",
    image: "https://i.postimg.cc/9QRBRfvq/calculator.png",
  },
  {
    id: 10,
    title: "25 + 5 Clock",
    text: "Single page web app built with React and TypeScript.",
    preview: "https://bozidarboze.github.io/clock/",
    code: "https://github.com/Bozidarboze/clock",
    image: "https://i.postimg.cc/Jhjcx27r/25-5-clock.png",
  },
  {
    id: 9,
    title: "Drum Machine",
    text: "Single page web app built with React and TypeScript you can play some tunes with.",
    preview: "https://bozidarboze.github.io/drum-machine/",
    code: "https://github.com/Bozidarboze/drum-machine",
    image: "https://i.postimg.cc/28JQDDVj/drum-machine.png",
  },
  {
    id: 8,
    title: "Markdown Previewer",
    text: "Single page web app built with React and TypeScript that can preview Markdown in realtime as you type in the editor.",
    preview: "https://bozidarboze.github.io/markdown-previewer/",
    code: "https://github.com/Bozidarboze/markdown-previewer",
    image: "https://i.postimg.cc/gjb4HnFn/markdown-previewer.png",
  },
  {
    id: 7,
    title: "Twitter Quote Generator",
    text: "Single page web app built with React and TypeScript that generates quotes you can post on your twitter feed.",
    preview: "https://bozidarboze.github.io/quote-generator/",
    code: "https://github.com/Bozidarboze/quote-generator",
    image: "https://i.postimg.cc/NMHpXRn3/quote-generator.png",
  },
  {
    id: 1,
    title: "KUD Ilinden",
    text: "Website built using Next.js for a Cultural Artistic Society.",
    preview: "https://kudilinden.vercel.app",
    code: "https://github.com/Bozidarboze/kudilinden",
    image: "https://i.postimg.cc/fbwNBRsq/kudilinden.png",
  },
  {
    id: 2,
    title: "CRWN Clothing",
    text: "eCommerce web app, built using React, Redux, Firebase and Stripe API.",
    preview: "https://bozidarboze.github.io/crwn/",
    code: "https://github.com/Bozidarboze/crwn",
    image: "https://i.postimg.cc/q75pqdfm/crwn.png",
  },
  {
    id: 3,
    title: "Facedetect",
    text: "Single page web app, built using React and REST API, that can detect a face on an image.",
    preview: "https://bozidarboze.github.io/facedetect",
    code: "https://github.com/Bozidarboze/facedetect",
    image: "https://i.postimg.cc/Fs3z61th/facedetect.png",
  },
  {
    id: 4,
    title: "Robofriends",
    text: "Single page web app, built with React, with a list of robofriends that you can search through.",
    preview: "https://bozidarboze.github.io/robofriends/",
    code: "https://github.com/Bozidarboze/robofriends",
    image: "https://i.postimg.cc/y6r8xcK1/robofriends.png",
  },
  {
    id: 5,
    title: "Dice Game",
    text: "Dice game web app, built with HTML, CSS and JQuery.",
    preview: "https://bozidarboze.github.io/dicegame/",
    code: "https://github.com/Bozidarboze/dicegame",
    image: "https://i.postimg.cc/g05grggy/dicegame.png",
  },
  {
    id: 6,
    title: "Drumkit",
    text: "Simple drumkit web app, built with HTML, CSS and Javascript.",
    preview: "https://bozidarboze.github.io/drumkit/",
    code: "https://github.com/Bozidarboze/drumkit",
    image: "https://i.postimg.cc/prQCGRRk/drumkit.png",
  },
];

export default Projects;
